services:
  client:
    build:
      context: client
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:
      - ./client:/opt/app
      - ./client/vite.config.docker.ts:/opt/app/vite.config.ts
      - node_modules_client:/opt/app/node_modules

  server:
    build:
      context: server
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - "./server/.env"
    volumes:
      - ./server:/opt/app
      - node_modules_server:/opt/app/node_modules

  db:
    image: postgres:16
    env_file:
      - "./server/.env"
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U slavic # check .env for user name
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - db_volume:/var/lib/postgresql/data
    

volumes:
  node_modules_client: {}
  node_modules_server: {}
  db_volume: {}
