services:
  client:
    image: "cr.magos.cc/slavtrash_client:latest"
    networks:
      - traefik_backbone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`slavic-trash.chickenkiller.com`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
      - "traefik.http.services.client.loadbalancer.server.port=8080"

  server:
    image: "cr.magos.cc/slavtrash_server:latest"
    env_file: ".env"
    volumes:
      - server_uploads:/opt/app/public/uploads
    networks:
      - traefik_public
      - traefik_backbone

  db:
    image: postgres:16
    env_file: ".env"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - traefik_backbone

volumes:
  server_uploads: {}
  db_volume: {}
  letsencrypt: {}

networks:
  traefik_public:
    external: true
  traefik_backbone:
    external: true