name: '[CI] Build and push images to private registry'

on:
  workflow_dispatch:
  push:
    branches:
      - 'build/**'

env:
  DOCKER_REGISTRY_URL: cr.magos.cc
  CLIENT_IMAGE_NAME: slavtrash_client
  SERVER_IMAGE_NAME: slavtrash_server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the release version
        id: strip-branch-name
        run: |
          release_version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/.*\///' | sed 's/[^a-zA-Z0-9._-]/_/g')
          echo "Building release version $release_version"
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
        shell: bash

      - name: Build and tag the client Docker image
        run: |
          docker build ./client --file client/Dockerfile.prod --tag ${{ env.CLIENT_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          docker tag ${{ env.DOCKER_REGISTRY_URL }}/${{ env.CLIENT_IMAGE_NAME }}:${{ env.RELEASE_VERSION }} ${{ env.DOCKER_REGISTRY_URL }}/${{ env.CLIENT_IMAGE_NAME }}:latest

      - name: Build and tag the server Docker image
        run: |
          docker build ./server --file server/Dockerfile --tag ${{ env.SERVER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          docker tag ${{ env.DOCKER_REGISTRY_URL }}/${{ env.SERVER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }} ${{ env.DOCKER_REGISTRY_URL }}/${{ env.SERVER_IMAGE_NAME }}:latest

      - name: Push images
        run: |
          docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.CLIENT_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.CLIENT_IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.SERVER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.SERVER_IMAGE_NAME }}:latest

      - name: Remove built images locally
        run: |
          docker rmi ${{ env.DOCKER_REGISTRY_URL }}/${{ env.CLIENT_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          docker rmi ${{ env.DOCKER_REGISTRY_URL }}/${{ env.CLIENT_IMAGE_NAME }}:latest
          docker rmi ${{ env.DOCKER_REGISTRY_URL }}/${{ env.SERVER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          docker rmi ${{ env.DOCKER_REGISTRY_URL }}/${{ env.SERVER_IMAGE_NAME }}:latest
