name: '[CI] - build and release'

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  call-build:
    uses: AlucardYanas/SLAVIC-TRASH/.github/workflows/build.yaml@main

  call-release:
    needs: call-build
    uses: AlucardYanas/SLAVIC-TRASH/.github/workflows/release.yaml@main
