name: '[CI] - sync production stack and deploy'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sync-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Add manager node to .ssh/known_hosts
        run: |
          mkdir -p ~/.ssh
          echo $(ssh-keyscan ${{ secrets.TARGET_HOST }}) > ~/.ssh/known_hosts

      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr
          path: production.stack.yml
          remote_path: ${{ secrets.TARGET_PATH }}
          remote_host: ${{ secrets.TARGET_HOST }}
          remote_user: ${{ secrets.TARGET_USER }}
          remote_key: ${{ secrets.TARGET_PRIVATE_KEY }}
    
      - name: Deploy production stack
        run: |
          echo "${{ secrets.TARGET_PRIVATE_KEY }}" > ~/id_rsa
          chmod 600 ~/id_rsa
          ssh -i ~/id_rsa -o StrictHostKeyChecking=no ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }} "docker stack deploy -c /opt/app/slavic_trash/production.stack.yml slavic_trash"
          rm ~/id_rsa
