name: '[CI] - send code to server'

on: workflow_dispatch

jobs:
  push-config:
    runs-on: ubuntu-latest
    steps:
      - name: Add manager node to .ssh/known_hosts
        run: |
          mkdir -p ~/.ssh
          echo $(ssh-keyscan ${{ secrets.TARGET_HOST }}) > ~/.ssh/known_hosts

      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude '.git*' --exclude '**/node_modules'
          path: .
          remote_path: ${{ secrets.TARGET_PATH }}
          remote_host: ${{ secrets.TARGET_HOST }}
          remote_user: ${{ secrets.TARGET_USER }}
          remote_key: ${{ secrets.TARGET_PRIVATE_KEY }}